Fixed missing doc step to create external network for consul compose example
Minor change to docs.

Due to the external network definition, a user must run `docker network create consul_istiomesh` first for the console docker-compose example. Otherwise they will get this when following the docs
```
ERROR: Network consul_istiomesh declared as external, but could not be found. Please create the network manually using `docker network create consul_istiomesh` and try again.
```